### ISSUE TITLE
Custom subdomains return SSL errors

### ISSUE THREAD

**Issue by jschlier** [plausible/hosting#17]
Hey there,

thanks for this great example repo.
I used this as the basis for our self-hosted Plausible installation and it works like a treat.

I encountered one problem with the custom subdomains though.
When calling the "custom." subdomain I always receive SSL Errors.
This is the output of a Curl request to the "custom." subdomain:

```
* Connected to custom.plausible.domain (Plausible IP) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS alert, internal error (592):
* error:14004438:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert internal error
* Closing connection 0
curl: (35) error:14004438:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert internal error
```

EDIT: I am using the provided Caddy reverse proxy.

**Comment by ukutaht** [comment]
Hey. Custom domains are not really supported in a self-hosted environment. For our cloud version we have a separate server that handles custom domains. I didn't see much reason to include it for self-hosters because you don't have problems with ad-blockers when self-hosting.

Can you give some details as to what you're trying to do?

**Comment by jschlier** [comment]
Ah, good to know. The option is there, therefore I kinda expected it to work.

We would not have any problems with ad-blockers if we were hosting on the same domain/server, that is true.

We have several websites across several servers/domains and figured we could host **one** instance of plausible on a dedicated server.
To collect the data from all domains we would like to use the custom subdomains that would redirect to our dedicated plausible server.

**Comment by ukutaht** [comment]
Gotcha. I don't believe there's any benefit in assigning custom domains for tracking purposes. You're already flying under the radar of all adblockers since your analytics server is a custom one. There should be no problem just using your self-hosted Plausible domain for all tracking across multiple websites.

We don't have any plans to support custom domains in the self-hosted context. I'll close this issue as wontfix. Please do let me know if you have any other feedback :)

**Comment by mannp** [comment]
Does this mean the custom domain option should not be used for self hosted instances and therefore the /js/plausible.js script should be used instead of the index.js? 

I ask as the plausible.js script seems to be borked and doesn't respect the BASE_URL

**Comment by ukutaht** [comment]
> @ukutaht Can I clarify then, does this mean the custom domain option should not be used for self hosted instances and therefore the /js/plausible.js script should be used instead of the index.js?

Yes

I will take a look at the BASE_URL issue

**Comment by mannp** [comment]
Thanks for the clarification and taking a look at the plausible script.

**Comment by mabasic** [comment]
Is there a way to make custom domains work with self hosted plausible? 

I find this feature useful because instead of serving the js file from the domain of the plausible server, I could serve it from the domain of the actual website.

This way I don't have to setup a plausible application for each domain in order to get this behaviour.

**Comment by ukutaht** [comment]
It's possible but not at the top of the priority list at the moment. Happy for people to contribute but there's just 1 of me, sorry. I'm currently focused on other features that many more people have requested.

**Comment by mabasic** [comment]
Happy to help with this. Can you give me some pointers on where to look?
