### ISSUE TITLE
Could not find probe endpoint documentation

### ISSUE THREAD

**Issue by kikinsama** [plausible/hosting#173]
I have deployed the docker image on a Kubernetes cluster. However, sometimes the connection to Clickhouse is lost, but the pod keeps running as if nothing had happened.

I would like to know what are the correct endpoints to configure at least as ReadinessProbe and LivenessProbe.

Thanks.

**Comment by ruslandoga** [comment]
👋 @kikinsama 

`GET /api/health` might work for Plausible: https://github.com/plausible/analytics/blob/1e38bd87714bf8e44b024d9bd1b76b9592c7646d/lib/plausible_web/router.ex#L258

It returns status=200 when PG and CH are reachable, and site cache is warmed up, and it returns status=500 otherwise: https://github.com/plausible/analytics/blob/1e38bd87714bf8e44b024d9bd1b76b9592c7646d/lib/plausible_web/controllers/api/external_controller.ex#L50-L81

Note however that Plausible already always attempts to reconnect to ClickHouse if the connection is lost (you should see that in `docker compose logs plausible`), so it doesn't need to be restarted for that to happen.
