### ISSUE TITLE
Instruction check fail. The CPU does not support SSE4.1 instruction set.

### ISSUE THREAD

**Issue by Brouilles** [plausible/hosting#29]
Hi, 
I have buy a server on Kimsufi. But I have the following error during docker-compose up:
```
plausible_events_db_1  | Instruction check fail. The CPU does not support SSE4.1 instruction set.
plausible_events_db_1  | Instruction check fail. The CPU does not support SSE4.1 instruction set.
```

And so `hosting_plausible_1` and ` hosting_plausible_events_db_1` exited. The CPU is an Intel  Atom N2800.
Thanks.

**Comment by RealOrangeOne** [comment]
I too have had this issue with a kimsufi server.

Unfortunately it's neither an issue with plausible, nor a fixable issue. The issue is that Clickhouse requires CPU instructions which are not available on the CPU kimsufi are providing. It's not possible to run Clickhouse on those machines, and therefore not possible to run plausible.

The only solution is to either change Kimsufi plan to a CPU which supports SSE4.1, move clickhouse onto its own server which does, or just run plausible elsewhere.

(As an aside, every other VPS provider i've seen uses CPUs with SSE4.1 support).

**Comment by Brouilles** [comment]
Thanks.
I have opted for a OVH VPS. It's working.
