### ISSUE TITLE
ARM Docker Image?

### ISSUE THREAD

**Issue by Brouilles** [plausible/hosting#31]
Hi!
I want to know if an ARM image is available? Compatible with the Raspberry Pi for exemple. It can be great ! But I don't know if dependencies are available for this architecture.

Matomo do (because the main dependencies is PHP). But with so many data I don't Care about.

Thanks and happy new year.

**Comment by ukutaht** [comment]
Hi,

We do not offer an ARM image, sorry. It's made complex by Clickhouse who only offer an official x86_64 build. If we want an ARM version we need to build Clickhouse from source in our build pipeline: https://clickhouse.tech/docs/en/operations/requirements/. I believe Posgres and Elixir are easier although I haven't looked into it that much.

We'd be very grateful for a contribution on this front. Since our production servers are x86 we just don't have much reason to build this.

**Comment by Brouilles** [comment]
Thanks for your answer 👍🏻
